export const USERS = [
  {
    id: 'u1',
    name: 'Александр Петров',
    email: 'alex@mail.ru',
    password: '123456',
    role: 'client',
    avatar: null,
    status: 'online',
  },
  {
    id: 'u2',
    name: 'Мария Сидорова',
    email: 'maria@mail.ru',
    password: '123456',
    role: 'client',
    avatar: null,
    status: 'offline',
  },
  {
    id: 'u3',
    name: 'Дмитрий Козлов',
    email: 'dmitry@mail.ru',
    password: '123456',
    role: 'client',
    avatar: null,
    status: 'online',
  },
  {
    id: 'op1',
    name: 'Анна Операторова',
    email: 'operator@shop.ru',
    password: 'operator123',
    role: 'operator',
    avatar: null,
    status: 'online',
  },
  {
    id: 'op2',
    name: 'Сергей Поддержкин',
    email: 'support@shop.ru',
    password: 'support123',
    role: 'operator',
    avatar: null,
    status: 'online',
  },
  {
    id: 'adm1',
    name: 'Администратор',
    email: 'admin@shop.ru',
    password: 'admin123',
    role: 'admin',
    avatar: null,
    status: 'online',
  },
];

export const DIALOGS = [
  {
    id: 'd1',
    clientId: 'u1',
    operatorId: 'op1',
    subject: 'Где мой заказ #45823?',
    status: 'open',
    priority: 'high',
    category: 'delivery',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    unreadClient: 0,
    unreadOperator: 2,
  },
  {
    id: 'd2',
    clientId: 'u1',
    operatorId: 'op2',
    subject: 'Возврат товара',
    status: 'resolved',
    priority: 'medium',
    category: 'returns',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    unreadClient: 0,
    unreadOperator: 0,
  },
  {
    id: 'd3',
    clientId: 'u2',
    operatorId: 'op1',
    subject: 'Проблема с оплатой',
    status: 'open',
    priority: 'high',
    category: 'payment',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    unreadClient: 1,
    unreadOperator: 0,
  },
  {
    id: 'd4',
    clientId: 'u3',
    operatorId: null,
    subject: 'Консультация по товару',
    status: 'pending',
    priority: 'low',
    category: 'consultation',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unreadClient: 0,
    unreadOperator: 1,
  },
  {
    id: 'd5',
    clientId: 'u2',
    operatorId: 'op2',
    subject: 'Не пришёл чек на email',
    status: 'closed',
    priority: 'low',
    category: 'other',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
    unreadClient: 0,
    unreadOperator: 0,
  },
];

export const MESSAGES = {
  d1: [
    {
      id: 'm1',
      dialogId: 'd1',
      senderId: 'u1',
      text: 'Здравствуйте! Хотел уточнить, где мой заказ #45823? Уже прошло 5 дней.',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
      id: 'm2',
      dialogId: 'd1',
      senderId: 'op1',
      text: 'Добрый день, Александр! Проверяю ваш заказ...',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    },
    {
      id: 'm3',
      dialogId: 'd1',
      senderId: 'op1',
      text: 'Ваш заказ находится в пути. По данным курьерской службы, доставка ожидается завтра с 10:00 до 18:00. Трек-номер: RU123456789.',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    },
    {
      id: 'm4',
      dialogId: 'd1',
      senderId: 'u1',
      text: 'Спасибо! А можно уточнить у курьера время доставки?',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    },
    {
      id: 'm5',
      dialogId: 'd1',
      senderId: 'op1',
      text: 'Да, конечно! Номер курьера придёт вам в SMS за час до доставки.',
      type: 'text',
      status: 'delivered',
      createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  ],
  d2: [
    {
      id: 'm6',
      dialogId: 'd2',
      senderId: 'u1',
      text: 'Хочу вернуть товар, не подошёл размер.',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: 'm7',
      dialogId: 'd2',
      senderId: 'op2',
      text: 'Здравствуйте! Понял вас. Для оформления возврата нужно заполнить форму на сайте и отправить товар по адресу: г. Москва, ул. Складская 5.',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    },
    {
      id: 'm8',
      dialogId: 'd2',
      senderId: 'u1',
      text: 'Всё понял, спасибо!',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    },
    {
      id: 'm9',
      dialogId: 'd2',
      senderId: 'op2',
      text: 'Пожалуйста! Ваше обращение закрыто. Если понадоббится помощь — обращайтесь!',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    },
  ],
  d3: [
    {
      id: 'm10',
      dialogId: 'd3',
      senderId: 'u2',
      text: 'Не могу оплатить заказ картой Visa, выдаёт ошибку "Транзакция отклонена".',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: 'm11',
      dialogId: 'd3',
      senderId: 'op1',
      text: 'Здравствуйте, Мария! Могу я уточнить — какой банк выпустил карту?',
      type: 'text',
      status: 'delivered',
      createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    },
  ],
  d4: [
    {
      id: 'm12',
      dialogId: 'd4',
      senderId: 'u3',
      text: 'Подскажите, в чём отличие модели iPhone 15 от iPhone 15 Pro?',
      type: 'text',
      status: 'sent',
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
  ],
  d5: [
    {
      id: 'm13',
      dialogId: 'd5',
      senderId: 'u2',
      text: 'Не получила чек на email после оплаты.',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    },
    {
      id: 'm14',
      dialogId: 'd5',
      senderId: 'op2',
      text: 'Добрый день! Чек повторно отправлен на ваш email. Проверьте папку "Спам".',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
    },
    {
      id: 'm15',
      dialogId: 'd5',
      senderId: 'u2',
      text: 'Нашла, спасибо!',
      type: 'text',
      status: 'read',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
    },
  ],
};

export const CATEGORIES = [
  { id: 'delivery', label: 'Доставка' },
  { id: 'payment', label: 'Оплата' },
  { id: 'returns', label: 'Возврат' },
  { id: 'consultation', label: 'Консультация' },
  { id: 'other', label: 'Прочее' },
];

export const QUICK_REPLIES = [
  'Здравствуйте! Чем могу помочь?',
  'Проверяю информацию, одну минуту...',
  'Спасибо за обращение! Ваш вопрос решён.',
  'Для уточнения деталей уточните номер заказа.',
  'Передаю ваш вопрос специалисту.',
];
